file_format: "1"
id: epsilon
name: shaoboi.epsilon 
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - epsilon_left
  - epsilon_right
